{{- if .Values.enabled -}}
{{- $db := .Values.database | default dict -}}

{{- $dbBlue := $db.blue | default dict -}}
{{- $dbGreen := $db.green | default dict -}}
{{- $search := .Values.search | default dict -}}
{{- $storage := .Values.storage | default dict -}}
{{- $storageBlue := $storage.blue | default dict -}}
{{- $storageGreen := $storage.green | default dict -}}
{{- $overlay := .Values.overlay | default dict -}}
apiVersion: gcp.liferay.com/v1alpha1
kind: LiferayInfrastructure

-- take out defualts
metadata:
    # checkov:skip=CKV_K8S_21:Namespace is set dynamically by Helm/ArgoCD
    annotations:
        argocd.argoproj.io/sync-wave: "-20"
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    commonTags:
        EnvironmentId: {{ .Values.environmentId }}
        ProjectId: {{ .Values.projectId }}
    database:
        databaseVersion: {{ $dbBlue.engineVersion | default "POSTGRES_16" | quote }}
        instanceType: {{ $dbBlue.instanceClass | default "db-custom-1-3840" | quote }}
    deletionProtection: {{ .Values.deletionProtection | default false }}
    environmentId: {{ .Values.environmentId }}
    overlay:
        enabled: {{ $overlay.enabled | default false }}
        githubRepo: {{ $overlay.githubRepo | default "" | quote }}
    projectId: {{ .Values.projectId }}
    storage:
     enableVersioning: {{ $storageBlue.enableVersioning | default true }}
     region: {{ $storageBlue.region | default  | quote }}

{{- end -}}